apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-routes
spec:
  http:
    - name: route-1
      match:
        paths:
          - /v1
      backends:
        - serviceName: whoami-1
          servicePort: 80
    - name: route-2
      match:
        paths:
          - /v2
      backends:
        - serviceName: whoami-2
          servicePort: 80
    - name: route-3
      match:
        paths:
          - /v3
      backends:
        - serviceName: whoami-3
          servicePort: 80
