apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami-2
  template:
    metadata:
      labels:
        app: whoami-2
    spec:
      containers:
      - name: whoami-2
        image: traefik/whoami  # Your Docker image
        ports:
        - containerPort: 80

---


apiVersion: v1
kind: Service
metadata:
  name: whoami-2
spec:
  selector:
    app: whoami-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
