apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bare-minimum-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Teodor-Vulev/test112.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
