apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd   # This must match where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix
    targetRevision: "2.10"  # or latest version
    path: manifests/apisix
    helm:
      skipCrds: true  # <--- IMPORTANT
      parameters:
        - name: gateway.type
          value: NodePort
        - name: ingress-controller.enabled
          value: "true"
        - name: ingress-controller.config.apisix.serviceNamespace
          value: apisix
        - name: dashboard.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
