apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bare-minimum-api
  namespace: argocd  # or whatever namespace Argo CD is in
spec:
  project: default
  source:
    repoURL: https://github.com/Teodor-Vulev/test112.git
    targetRevision: main
    path: manifests/bare-minimum-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# 