apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd  # or whatever namespace Argo CD is in
spec:
  project: default
  source:
    repoURL: https://github.com/Teodor-Vulev/test112.git
    targetRevision: main
    path: manifests/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  info:
  - name: "Example:"
    value: >-
      https://example.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
